# Generated by Django 6.0.3 on 2026-04-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='date_returned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
