# Generated by Django 6.0.3 on 2026-04-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_ticket_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='test_field',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
