# Generated by Django 6.0.3 on 2026-04-11 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_ticket_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='test_field',
        ),
    ]
