# Generated by Django 6.0.3 on 2026-04-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_remove_ticket_test_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
