# Generated by Django 6.0.3 on 2026-04-18 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
